services:
  backend:
    build:
      context: ./backend
    ports:
      - "5050:5000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
